In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


from sklearn.decomposition import PCA
from scipy.stats import zscore

In [2]:
# Read the dataset

mpg_df = pd.read_csv("cars-dataset.csv")  

# drop the car name column as it is useless for the model
car_name = mpg_df['car name']
mpg_df = mpg_df.drop('car name', axis=1)
mpg_df.head()

   cyl   disp   hp    wt   acc  yr   mpg
0    8  307.0  130  3504  12.0  70  18.0
1    8  350.0  165  3693  11.5  70  15.0
2    8  318.0  150  3436  11.0  70  18.0
3    8  304.0  150  3433  12.0  70  16.0
4    8  302.0  140  3449  10.5  70  17.0

In [3]:
mpg_df.dtypes

cyl       int64
disp    float64
hp       object
wt        int64
acc     float64
yr        int64
mpg     float64
dtype: object

In [4]:
# cleaning the horsepower
#mpg_df['hp'].value_counts()
#horsepower = mpg_df['hp'].loc[mpg_df['hp'] != '?']
#horsepower
#hpmean = horsepower.astype(str).astype(int).mean()
#mpg_df['hp'] = mpg_df['hp'].replace('?',hpmean).astype(int)

In [5]:
mpg_df.dtypes

cyl       int64
disp    float64
hp       object
wt        int64
acc     float64
yr        int64
mpg     float64
dtype: object

In [6]:
mpg_df.isnull().sum()

cyl     0
disp    0
hp      0
wt      0
acc     0
yr      0
mpg     0
dtype: int64

In [7]:
mpg_df.isna().sum()

cyl     0
disp    0
hp      0
wt      0
acc     0
yr      0
mpg     0
dtype: int64

In [8]:
mpg_df.columns

Index(['cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'mpg'], dtype='object')

In [9]:
mpg_df.shape

(398, 7)

In [10]:
mpg_df.describe().T 
#hp not seen in the list

,count,mean,std,min,25%,50%,75%,max
cyl,398.0,5.454774,1.701004,3.0,4.000,4.0,8.000,8.0
disp,398.0,193.425879,104.269838,68.0,104.250,148.5,262.000,455.0
wt,398.0,2970.424623,846.841774,1613.0,2223.750,2803.5,3608.000,5140.0
acc,398.0,15.568090,2.757689,8.0,13.825,15.5,17.175,24.8
yr,398.0,76.010050,3.697627,70.0,73.000,76.0,79.000,82.0
mpg,398.0,23.514573,7.815984,9.0,17.500,23.0,29.000,46.6

In [11]:
# horsepower is an object type though it is supposed to be numeric. Check if all the rows in this column are digits 
temp = pd.DataFrame(mpg_df.hp.str.isdigit())  # if the string is made of digits store True else False  in the hp column 
temp[temp['hp'] == False]   # from temp take only those rows where hp has false

# On inspecting records number 32, 126 etc, we find "?" in the columns. Replace them with "nan"
#Replace them with nan and remove the records from the data frame that have "nan"
mpg_df = mpg_df.replace('?', np.nan)
mpg_df = mpg_df.apply(lambda x: x.fillna(x.median()),axis=0)


# converting the hp column from object / string type to float
mpg_df['hp'] = mpg_df['hp'].astype('float64')

In [12]:
#Checking the outlier of horsepower
mpg_df.loc[mpg_df['hp'] > 10000]

Empty DataFrame
Columns: [cyl, disp, hp, wt, acc, yr, mpg]
Index: []

In [13]:
mpg_df.describe().T

,count,mean,std,min,25%,50%,75%,max
cyl,398.0,5.454774,1.701004,3.0,4.000,4.0,8.000,8.0
disp,398.0,193.425879,104.269838,68.0,104.250,148.5,262.000,455.0
hp,398.0,104.304020,38.222625,46.0,76.000,93.5,125.000,230.0
wt,398.0,2970.424623,846.841774,1613.0,2223.750,2803.5,3608.000,5140.0
acc,398.0,15.568090,2.757689,8.0,13.825,15.5,17.175,24.8
yr,398.0,76.010050,3.697627,70.0,73.000,76.0,79.000,82.0
mpg,398.0,23.514573,7.815984,9.0,17.500,23.0,29.000,46.6

In [14]:
# This is done using scatter matrix function which creates a dashboard reflecting useful information about the dimensions
# The result can be stored as a .png file and opened in say, paint to get a larger view 

#mpg_df_attr = mpg_df.iloc[:, 0:9]
#mpg_df_attr['dispercyl'] = mpg_df_attr['disp'] / mpg_df_attr['cyl']
#sns.pairplot(mpg_df_attr, diag_kind='kde', hue = 'mpg')   # to plot density curve instead of histogram

In [ ]:
#Visually inspect the covariance between independent dimensions and between mpg and independent dimensions

sns.pairplot(mpg_df, diag_kind='kde', hue = 'mpg')

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\nonparametric\bandwidths.py:20: RuntimeWarning: invalid value encountered in minimum
  return np.minimum(np.std(X, axis=0, ddof=1), IQR)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\nonparametric\kde.py:488: RuntimeWarning: invalid value encountered in true_divide
  binned = fast_linbin(X, a, b, gridsize) / (delta * nobs)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\nonparametric\kdetools.py:34: RuntimeWarning: invalid value encountered in double_scalars
  FAC1 = 2*(np.pi*bw/RANGE)**2

In [ ]:
plt.figure(figsize=(12,10))
sns.heatmap(mpg_df.corr(),annot=True)

In [ ]:
#Scatter matix
pd.scatter_matrix(mpg_df, alpha=0.2, figsize=(8, 8))
plt.show()

In [ ]:
mpg_df.dtypes

In [ ]:
# Split the wine data into separate training (70%) and test (30%) sets and then standardize it to unit variance:
X = mpg_df[mpg_df.columns[1:-1]]
y = mpg_df["mpg"]

In [ ]:
# We transform (centralize) the entire X (independent variable data) to zscores through transformation. We will create the PCA dimensions
# on this distribution. 
sc = StandardScaler()
X_std =  sc.fit_transform(X)          
cov_matrix = np.cov(X_std.T)
print('Covariance Matrix \n%s', cov_matrix)

In [ ]:
X_std=StandardScaler().fit_transform(X)
#Dimentioanlity Reduction by PCA
from sklearn.decomposition import PCA
# Perform PCA
pca_auto= PCA(n_components=10)
pca_auto.fit(X_std)
pca_auto.explained_variance_ratio_.sum()

In [ ]:
cluster_range = range( 2, 8)   # expect 3 to four clusters from the pair panel visual inspection hence restricting from 2 to 6
cluster_errors = []
for num_clusters in cluster_range:
  clusters = KMeans( num_clusters, n_init = 5)
  clusters.fit(X)
  labels = clusters.labels_
  centroids = clusters.cluster_centers_
  cluster_errors.append( clusters.inertia_ )
clusters_df = pd.DataFrame( { "num_clusters":cluster_range, "cluster_errors": cluster_errors } )
clusters_df